---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## NEWA @ Cornell

Create all possible combinations of station-year-month:
```{r}
stations <- c("acc", "kalb", "alb")
years <- 2015:2020
months <- 1:12

combinations <- data.frame(station = rep(stations, each = length(years) * length(months)),
                           year = rep(years, each = length(months)),
                           month = months,
                           downloaded = FALSE)

knitr::kable(head(combinations, 10))
```

Create RSelenium session
```{r, eval = FALSE}
# Create RSelenium session
rD <- RSelenium::rsDriver(browser = "firefox", port = 4548L, verbose = FALSE)
```

Retrieve data
```{r, eval = FALSE}
# Path to the output directory
outputdir <- getwd()

# Create progress bar
pb <- progress::progress_bar$new(
    format = "(:current/:total) [:bar] :percent",
    total = nrow(combinations), clear = FALSE, width = 80)
for (i in seq_len(nrow(combinations))) {
  tryCatch({
    # Check if the data has been downloaded
    if (!combinations$downloaded[i]) {
      # Call scrappy
      scrappy::newa_nrcc(client = rD$client, 
                         year = combinations$year[i],
                         month = combinations$month[i],
                         station = combinations$station[i], 
                         path = outputdir)
      combinations$downloaded[i] <- TRUE
    }
  }, error = function(e) {
    message("Error processing combination with index ", i)
    warning(e)
  })
  # Update progress bar
  pb$tick()
}

# Stop server
rD$server$stop()
```

Post-processing: combine individual CSV files by station name:
```{r, eval = FALSE}
stations <- c("acc", "kalb", "alb")
states <- c("NY", "NY", "NY")
for (s in seq_len(length(stations))) {
  st <- stations[s]
  message("Processing: ", st)
  files <- list.files(outputdir, pattern = st, full.names = TRUE)
  if (length(files) > 0) {
    message(length(files), " files found...")
    combined_data <- NULL
    for(f in files) {
      aux <- read.csv(f)
      if (is.null(combined_data)) {
        combined_data <- aux
      } else {
        combined_data <- rbind(combined_data, aux)
      }
    }
    combined_data$State <- states[s]
    write.csv(combined_data, paste0(st, ".csv"), row.names = FALSE)
  }
}
```
